#include <vulkan/vulkan.h>
#include <cstdio>
#define P(name) printf("%-52s = %d\n", #name, (int)name)
int main() {
    P(VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO);
    P(VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET);
    P(VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO);
    P(VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO);
    P(VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO);
    P(VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO);
    P(VK_STRUCTURE_TYPE_MEMORY_BARRIER);
    P(VK_STRUCTURE_TYPE_SUBMIT_INFO);
    P(VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT);
    return 0;
}
